@ShopApp_HostAddress = http://localhost:5228

###
GET {{ShopApp_HostAddress}}/api/product/

###
GET {{ShopApp_HostAddress}}/api/product/4

###
GET {{ShopApp_HostAddress}}/api/product/search

###
GET {{ShopApp_HostAddress}}/api/product/search?title=Phone+2

###
DELETE {{ShopApp_HostAddress}}/api/product/2

###
POST {{ShopApp_HostAddress}}/api/product
Content-Type: application/json

{
  "Title": "Milk",
  "Price": 60.902
}

###
PUT {{ShopApp_HostAddress}}/api/product/2
Content-Type: application/json

{
  "Title": "Milk",
  "Price": 78.902
}


###
POST {{ShopApp_HostAddress}}/api/category
Content-Type: application/json

{
  "Title": "Phone",
  "Description": "none",
  "Image": "none",
  "CreatedAt": "none",
  "UpdateddAt": "none",
  "isShow": true
}